version: '3'

services:

  # redis:
  #   image: redis
  #   restart: always
  #   volumes:
  #     - ${REDIS_CONF_HOST}:/usr/local/etc/redis/redis.conf
  #     - ${REDIS_DATA_HOST}:/data
  #   command: redis-server /usr/local/etc/redis/redis.conf
  #
  # rebrow:
  #   image: marian/rebrow
  #   restart: always
  #   ports:
  #     - 5001:5001

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #   volumes:
  #     - ${MONGO_CONF_HOST}:${MONGO_CONF_CONTAINER}
  #     - ${MONGO_DATA_HOST}:/data/db
  #   # command: --config ${MONGO_CONF_CONTAINER}
  #
  # mongoclient:
  #   image: mongoclient/mongoclient
  #   restart: always
  #   ports:
  #     - 3300:3000

  pm2:
    build: ./pm2
    restart: always
    environment:
      # MONGO_DB_NAME: ${MONGO_DB_NAME}
      # MONGO_USERNAME: ${MONGO_USERNAME}
      # MONGO_PASSWORD: ${MONGO_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./pm2/var:/var
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 3000:3000
    working_dir: ${APP_PATH_CONTAINER}
    command: npm run start

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MARIA_DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  # composer:
  #   image: composer:1.6
  #   volumes:
  #     - ${API_PATH_HOST}:${API_PATH_CONTAINER}
  #   working_dir: ${API_PATH_CONTAINER}
  #   command: composer install
